// resources/assets/js/components/SocialMy.vue
<template>
    <div class="fixed-bottom d-flex justify-content-between p-4">
        <div>
            <a href="https://twitter.com/renatosoarespro"><i class="fa-2x fab fa-twitter-square"></i></a>
            <a href="https://github.com/renatosoares"><i class="fa-2x fab fa-github-square"></i></a>
            <a href="https://www.linkedin.com/in/renatosoarespro/"><i class="fa-2x fab fa-linkedin"></i></a>
        </div>
        <div>
            <h1>Systems Developer</h1>
            <span>Renato Soares </span><i class="fas fa-coffee"></i> <i class="fas fa-desktop"></i> $_
        </div>
    </div>
</template>

<script lang="ts" src="./SocialMy.vue.ts"></script>

// src/components/atoms/SocialMy/index.tsx
import React from "react";
import SocialMyStyles from "./SocialMy.module.scss";
import "./styles.scss";

const SocialMy = () => (
  <div className={[SocialMyStyles.socialMy, "social-my"].join(" ")}>
    <div className="social-links">
      <a href="//codepen.io/renatosoares" target="_blank" rel="noreferrer">
        codepen&nbsp;
      </a>
      <a
        href="//codesandbox.io/u/renatosoares"
        target="_blank"
        rel="noreferrer"
      >
        codesandbox&nbsp;
      </a>
      <a href="//github.com/renatosoares" target="_blank" rel="noreferrer">
        github&nbsp;
      </a>
      <a
        href="//hub.docker.com/u/renatosoarespro/starred"
        target="_blank"
        rel="noreferrer"
      >
        docker&nbsp;
      </a>
      <a
        href="//jsfiddle.net/user/renatosoarespro"
        target="_blank"
        rel="noreferrer"
      >
        jsfiddle&nbsp;
      </a>
      <a
        href="//linkedin.com/in/renatosoarespro"
        target="_blank"
        rel="noreferrer"
      >
        linkedin&nbsp;
      </a>
      <a href="//repl.it/@renatosoarespro" target="_blank" rel="noreferrer">
        repl&nbsp;
      </a>
      <a href="//twitter.com/renatosoarespro" target="_blank" rel="noreferrer">
        twitter&nbsp;
      </a>
      <a href="//wakatime.com/@renatosoares" target="_blank" rel="noreferrer">
        wakatime&nbsp;
      </a>
    </div>
    <div>
      <h1>Systems Developer</h1>
      <span>Renato Soares </span>
      <i className="fas fa-coffee"></i>
      <i className="fas fa-desktop"></i> $_
    </div>
  </div>
);

export default SocialMy;
